

enum class Token {
  TOK_EXCL = '!',
  TOK_PERCENT = '%',
  TOK_CARET = '^',
  TOK_TILDE = '~',
  TOK_LANGLE = '<',
  TOK_EQUALS = '=',
  TOK_RANGLE = '>',
  TOK_MINUS = '-',
  TOK_COMMA = ',',
  TOK_PIPE = '|',
  TOK_SEMICOLON = ';',
  TOK_COLON = ':',
  TOK_QUESTION = '?',
  TOK_SLASH = '/',
  TOK_DOT = '.',
  TOK_LPAREN = '(',
  TOK_RPAREN = ')',
  TOK_LBRACKET = '[',
  TOK_RBRACKET = ']',
  TOK_LCURLY = '{',
  TOK_RCURLY = '}',
  TOK_TIMES = '*',
  TOK_AMP = '&',
  TOK_PLUS = '+',
  TOK_CARET_EQ = 0x80 | '^',
  TOK_TILDE_EQ = 0x80 | '~',
  TOK_LANGLE_EQ = 0x80 | '<',
  TOK_EQUALS_EQ = 0x80 | '=',
  TOK_RANGLE_EQ = 0x80 | '>',
  TOK_PIPE_EQ = 0x80 | '|',
  TOK_MINUS_EQ = 0x80 | '-',
  TOK_EXCL_EQ = 0x80 | '!',
  TOK_TIMES_EQ = 0x80 | '*',
  TOK_AMP_EQ = 0x80 | '&',
  TOK_PERCENT_EQ = 0x80 | '%',
  TOK_PLUS_EQ = 0x80 | '+',
  TOK_LEFTSHIFT = 0x100,
  TOK_RSHIFT = 0x101,
  TOK_AMP_AMP = 0x102,
  TOK_STRING,
  TOK_CHAR,
  TOK_KEYWORD,
  TOK_IDENTIFIER,
};


